php:
  preset: laravel
  risky: true
  enabled:
    - long_array_syntax
  disabled:
    - align_double_arrow
  finder:
    exclude:
      - modules
      - node_modules
      - storage
      - vendor
    name: "*.php"
    not-name: "*.blade.php"
# php:
#   preset: laravel
#   disabled:
#     - unused_use
#   finder:
#     not-name:
#       - index.php
#       - server.php
# js:
#   finder:
#     not-name:
#       - webpack.mix.js
# css: true
